/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.java.macro;

<<<<<<< HEAD
<<<<<<< HEAD
class MHeader {

  MHeader() {
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("/* This file was generated by SableCC's ObjectMacro. */");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

=======
import java.util.*;

public class MHeader extends Macro{



    public MHeader(){


=======
import java.util.*;

public class MHeader extends Macro{



    public MHeader(){


>>>>>>> object-macro2.1

    }





    @Override
    void apply(
            InternalsInitializer internalsInitializer){
<<<<<<< HEAD

        internalsInitializer.setHeader(this);
    }

   @Override
    public String build(){

        BuildState buildState = this.build_state;

        if(buildState == null){
            buildState = new BuildState();
        }
        else if(buildState.getExpansion() == null){
            throw ObjectMacroException.cyclicReference("Header");
        }
        else{
            return buildState.getExpansion();
        }
        this.build_state = buildState;

        

        

        StringBuilder sb0 = new StringBuilder();

        sb0.append("/* This file was generated by SableCC's ObjectMacro. */");

        buildState.setExpansion(sb0.toString());
        return sb0.toString();
    }

=======

        internalsInitializer.setHeader(this);
    }

   @Override
    public String build(){

        BuildState buildState = this.build_state;

        if(buildState == null){
            buildState = new BuildState();
        }
        else if(buildState.getExpansion() == null){
            throw ObjectMacroException.cyclicReference("Header");
        }
        else{
            return buildState.getExpansion();
        }
        this.build_state = buildState;

        

        

        StringBuilder sb0 = new StringBuilder();

        sb0.append("/* This file was generated by SableCC's ObjectMacro. */");

        buildState.setExpansion(sb0.toString());
        return sb0.toString();
    }

>>>>>>> object-macro2.1
    @Override
    String build(Context context) {
        return build();
    }
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> Mise à jour Visiteur - Build OK
}
=======
}
>>>>>>> Correctifs objectmacro2-java(back)
=======
}
>>>>>>> object-macro2.1
