/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.java.macro;

<<<<<<< HEAD
public class MInternalMacroField {

  private final String pName;
  private final MInternalMacroField mInternalMacroField = this;

  public MInternalMacroField(String pName) {
    if(pName == null) throw new NullPointerException();
    this.pName = pName;
  }

  String pName() {
    return this.pName;
  }

  private String rName() {
    return this.mInternalMacroField.pName();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    sb.append("    private Map<Context, InternalValue> list_");
=======
    sb.append("    private Map<Context, Macro[]> list_");
>>>>>>> Java code generation Objectmacro 2 using the lib ObjectMacro 1
=======
    sb.append("    private Map<Context, List<Macro>> list_");
>>>>>>> Removed in constructor initialization and add lazy initialization
=======
    sb.append("    private Map<Context, InternalValue> list_");
>>>>>>> Add structure which contains list of macros and the context associated
    sb.append(rName());
    sb.append(" = new LinkedHashMap<>();");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }
=======
public class MInternalMacroField extends Macro{
>>>>>>> Changement Objectmacro-back

    private String field_Name;

    public MInternalMacroField(String pName){

        this.setPName(pName);
    }

    private void setPName(String pName){
        if(pName == null){
            throw ObjectMacroException.parameterNull("Name");
        }

        this.field_Name = pName;
    }

    private String buildName(){

        return this.field_Name;
    }

    private String getName(){

        return this.field_Name;
    }

    @Override
    void apply(
            InternalsInitializer internalsInitializer){

        internalsInitializer.setInternalMacroField(this);
    }

    @Override
    public String build(){

        String local_expansion = this.expansion;

        if(local_expansion != null){
            return local_expansion;
        }

        StringBuilder sb0 = new StringBuilder();

        sb0.append("    private Map<Context, Macro[]> list_");
        sb0.append(buildName());
        sb0.append(" = new LinkedHashMap<>();");

        local_expansion = sb0.toString();
        this.expansion = local_expansion;
        return local_expansion;
    }

    @Override
    String build(Context context) {
        return build();
    }
}
