/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.java.macro;

<<<<<<< HEAD
public class MPackageDeclaration {

  private final String pPackageName;
  private final MPackageDeclaration mPackageDeclaration = this;

  public MPackageDeclaration(String pPackageName) {
    if(pPackageName == null) throw new NullPointerException();
    this.pPackageName = pPackageName;
  }

  String pPackageName() {
    return this.pPackageName;
  }

  private String rPackageName() {
    return this.mPackageDeclaration.pPackageName();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("package ");
    sb.append(rPackageName());
    sb.append(";");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

=======
import java.util.*;

public class MPackageDeclaration extends Macro{

    private String field_PackageName;

    public MPackageDeclaration(String pPackageName){

        this.setPPackageName(pPackageName);
    }

    private void setPPackageName(String pPackageName){
        if(pPackageName == null){
            throw ObjectMacroException.parameterNull("PackageName");
        }

        this.field_PackageName = pPackageName;
    }

    private String buildPackageName(){

        return this.field_PackageName;
    }

    private String getPackageName(){

        return this.field_PackageName;
    }
    @Override
    void apply(
            InternalsInitializer internalsInitializer){

        internalsInitializer.setPackageDeclaration(this);
    }

    @Override
    public String build(){

        BuildState buildState = this.build_state;

        if(buildState == null){
            buildState = new BuildState();
        }
        else if(buildState.getExpansion() == null){
            throw ObjectMacroException.cyclicReference("PackageDeclaration");
        }
        else{
            return buildState.getExpansion();
        }
        this.build_state = buildState;

        
        
        StringBuilder sb0 = new StringBuilder();

        sb0.append("package ");
        sb0.append(buildPackageName());
        sb0.append(";");

        buildState.setExpansion(sb0.toString());
        return sb0.toString();
    }

    @Override
    String build(Context context) {
        return build();
    }
>>>>>>> Mise à jour Visiteur - Build OK
}
