/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.java.macro;

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> Revert "Changement Objectmacro-back"
=======
>>>>>>> Revert "MaJ Fichier de Macro + Generation"
import java.util.*;

public class MSetInternal {

  private final String pMacroName;
  private final String pParamName;
  private final String pContext;
  private final MSetInternal mSetInternal = this;
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
  private final List<Object> eParamRef_StringBuilderBuild = new LinkedList<Object>();
=======
  private final List<Object> eMacroArg_StringBuilderBuild = new LinkedList<Object>();
>>>>>>> Java code generation Objectmacro 2 using the lib ObjectMacro 1
=======
  private final List<Object> eParamRef_StringBuilderBuild = new LinkedList<Object>();
>>>>>>> Allow to set internals with string and macro by adding a structure containing the macro and parameters and internals name
=======
  private final List<Object> eParamRef_StringBuilderBuild = new LinkedList<Object>();
>>>>>>> Revert "Changement Objectmacro-back"
=======
  private final List<Object> eParamRef_StringBuilderBuild = new LinkedList<Object>();
>>>>>>> Revert "MaJ Fichier de Macro + Generation"

  public MSetInternal(String pMacroName, String pParamName, String pContext) {
    if(pMacroName == null) throw new NullPointerException();
    this.pMacroName = pMacroName;
    if(pParamName == null) throw new NullPointerException();
    this.pParamName = pParamName;
    if(pContext == null) throw new NullPointerException();
    this.pContext = pContext;
  }

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> Allow to set internals with string and macro by adding a structure containing the macro and parameters and internals name
=======
>>>>>>> Revert "Changement Objectmacro-back"
=======
>>>>>>> Revert "MaJ Fichier de Macro + Generation"
  public MParamRef newParamRef(String pName) {
    MParamRef lParamRef = new MParamRef(pName);
    this.eParamRef_StringBuilderBuild.add(lParamRef);
    return lParamRef;
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
  public MMacroArg newMacroArg(String pName) {
    MMacroArg lMacroArg = new MMacroArg(pName);
    this.eMacroArg_StringBuilderBuild.add(lMacroArg);
    return lMacroArg;
>>>>>>> Java code generation Objectmacro 2 using the lib ObjectMacro 1
=======
>>>>>>> Allow to set internals with string and macro by adding a structure containing the macro and parameters and internals name
=======
>>>>>>> Revert "Changement Objectmacro-back"
=======
>>>>>>> Revert "MaJ Fichier de Macro + Generation"
  }

  public MStringBuilderBuild newStringBuilderBuild(String pIndexBuilder) {
    MStringBuilderBuild lStringBuilderBuild = new MStringBuilderBuild(pIndexBuilder);
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    this.eParamRef_StringBuilderBuild.add(lStringBuilderBuild);
=======
    this.eMacroArg_StringBuilderBuild.add(lStringBuilderBuild);
>>>>>>> Java code generation Objectmacro 2 using the lib ObjectMacro 1
=======
    this.eParamRef_StringBuilderBuild.add(lStringBuilderBuild);
>>>>>>> Allow to set internals with string and macro by adding a structure containing the macro and parameters and internals name
=======
    this.eParamRef_StringBuilderBuild.add(lStringBuilderBuild);
>>>>>>> Revert "Changement Objectmacro-back"
=======
    this.eParamRef_StringBuilderBuild.add(lStringBuilderBuild);
>>>>>>> Revert "MaJ Fichier de Macro + Generation"
    return lStringBuilderBuild;
  }

  String pMacroName() {
    return this.pMacroName;
  }

  String pParamName() {
    return this.pParamName;
  }

  String pContext() {
    return this.pContext;
  }

  private String rMacroName() {
    return this.mSetInternal.pMacroName();
  }

  private String rParamName() {
    return this.mSetInternal.pParamName();
  }

  private String rContext() {
    return this.mSetInternal.pContext();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("        m");
    sb.append(rMacroName());
    sb.append(".set");
    sb.append(rParamName());
    sb.append("(");
    sb.append(rContext());
    sb.append(", ");
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    for(Object oParamRef_StringBuilderBuild : this.eParamRef_StringBuilderBuild) {
      sb.append(oParamRef_StringBuilderBuild.toString());
=======
    for(Object oMacroArg_StringBuilderBuild : this.eMacroArg_StringBuilderBuild) {
      sb.append(oMacroArg_StringBuilderBuild.toString());
>>>>>>> Java code generation Objectmacro 2 using the lib ObjectMacro 1
=======
    for(Object oParamRef_StringBuilderBuild : this.eParamRef_StringBuilderBuild) {
      sb.append(oParamRef_StringBuilderBuild.toString());
>>>>>>> Allow to set internals with string and macro by adding a structure containing the macro and parameters and internals name
=======
    for(Object oParamRef_StringBuilderBuild : this.eParamRef_StringBuilderBuild) {
      sb.append(oParamRef_StringBuilderBuild.toString());
>>>>>>> Revert "Changement Objectmacro-back"
=======
    for(Object oParamRef_StringBuilderBuild : this.eParamRef_StringBuilderBuild) {
      sb.append(oParamRef_StringBuilderBuild.toString());
>>>>>>> Revert "MaJ Fichier de Macro + Generation"
    }
    sb.append(");");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
import java.util.*;

>>>>>>> Mise à jour Visiteur - Build OK
public class MSetInternal extends Macro{
>>>>>>> Changement Objectmacro-back
=======
>>>>>>> Revert "Changement Objectmacro-back"
=======
public class MSetInternal extends Macro{
>>>>>>> MaJ Fichier de Macro + Generation
=======
>>>>>>> Revert "MaJ Fichier de Macro + Generation"

<<<<<<< HEAD
=======
    private String field_MacroName;
    private String field_ParamName;
    private String field_Context;
    private final List<Macro> list_ListParam;
    private DSeparator ListParamSeparator;

    private DBeforeFirst ListParamBeforeFirst;

    private DAfterLast ListParamAfterLast;

    private DNone ListParamNone;
    private final InternalValue ListParamValue;

    private final Context ListParamContext = new Context();

    public MSetInternal(String pMacroName, String pParamName, String pContext){

        this.setPMacroName(pMacroName);        this.setPParamName(pParamName);        this.setPContext(pContext);

    this.list_ListParam = new ArrayList<>();

    this.ListParamValue = new InternalValue(this.list_ListParam, this.ListParamContext);
    }

    private void setPMacroName( String pMacroName ){
        if(pMacroName == null){
            throw ObjectMacroException.parameterNull("MacroName");
        }

        this.field_MacroName = pMacroName;
    }
    private void setPParamName( String pParamName ){
        if(pParamName == null){
            throw ObjectMacroException.parameterNull("ParamName");
        }

        this.field_ParamName = pParamName;
    }
    private void setPContext( String pContext ){
        if(pContext == null){
            throw ObjectMacroException.parameterNull("Context");
        }

        this.field_Context = pContext;
    }
    public void addListParam(MParamRef macro){
        if(macro == null){
            throw ObjectMacroException.parameterNull("ListParam");
        }
                if(this.build_state != null){
            throw ObjectMacroException.cannotModify("ParamRef");
        }

        this.list_ListParam.add(macro);
    }
    public void addListParam(MStringBuilderBuild macro){
        if(macro == null){
            throw ObjectMacroException.parameterNull("ListParam");
        }
                if(this.build_state != null){
            throw ObjectMacroException.cannotModify("StringBuilderBuild");
        }

        this.list_ListParam.add(macro);
    }

    private String buildMacroName(){

        return this.field_MacroName;
    }
    private String buildParamName(){

        return this.field_ParamName;
    }
    private String buildContext(){

        return this.field_Context;
    }
    private String buildListParam(){
        StringBuilder sb = new StringBuilder();
        Context local_context = ListParamContext;
        List<Macro> macros = this.list_ListParam;

        int i = 0;
        int nb_macros = macros.size();
        String expansion = null;

        if(this.ListParamNone != null){
            sb.append(this.ListParamNone.apply(i, "", nb_macros));
        }

        for(Macro macro : macros){
            expansion = macro.build(local_context);

            if(this.ListParamBeforeFirst != null){
                expansion = this.ListParamBeforeFirst.apply(i, expansion, nb_macros);
            }

            if(this.ListParamAfterLast != null){
                expansion = this.ListParamAfterLast.apply(i, expansion, nb_macros);
            }

            if(this.ListParamSeparator != null){
                expansion = this.ListParamSeparator.apply(i, expansion, nb_macros);
            }

            sb.append(expansion);
            i++;
        }

        return sb.toString();
    }

    private String getMacroName(){

        return this.field_MacroName;
    }
    private String getParamName(){

        return this.field_ParamName;
    }
    private String getContext(){

        return this.field_Context;
    }
    private InternalValue getListParam(){
        return this.ListParamValue;
    }
    private void initListParamInternals(Context context){
        for(Macro macro : this.list_ListParam){
            macro.apply(new InternalsInitializer("ListParam"){
@Override
void setParamRef(MParamRef mParamRef){

    
    
}@Override
void setStringBuilderBuild(MStringBuilderBuild mStringBuilderBuild){

    
    
}
});
        }
    }

    private void initListParamDirectives(){
        
    }
    @Override
    void apply(
            InternalsInitializer internalsInitializer){

        internalsInitializer.setSetInternal(this);
    }

   @Override
    public String build(){

        BuildState buildState = this.build_state;

        if(buildState == null){
            buildState = new BuildState();
        }
        else if(buildState.getExpansion() == null){
            throw ObjectMacroException.cyclicReference("SetInternal");
        }
        else{
            return buildState.getExpansion();
        }
        this.build_state = buildState;

        initListParamDirectives();

        initListParamInternals(null);

        StringBuilder sb0 = new StringBuilder();

        sb0.append("        m");
        sb0.append(buildMacroName());
        sb0.append(".set");
        sb0.append(buildParamName());
        sb0.append("(");
        sb0.append(buildContext());
        sb0.append(", ");
        sb0.append(buildListParam());
        sb0.append(");");

        buildState.setExpansion(sb0.toString());
        return sb0.toString();
    }

    @Override
    String build(Context context) {
        return build();
    }
<<<<<<< HEAD
>>>>>>> Mise à jour Visiteur - Build OK
}
=======
}
>>>>>>> Correctifs objectmacro2-java(back)
