/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.java.macro;

<<<<<<< HEAD
<<<<<<< HEAD
public class MStringBuilderBuild {
=======
import java.util.*;

public class MStringBuilderBuild extends Macro{
<<<<<<< HEAD
>>>>>>> Mise à jour Visiteur - Build OK

  private final String pIndexBuilder;
  private final MStringBuilderBuild mStringBuilderBuild = this;

  public MStringBuilderBuild(String pIndexBuilder) {
    if(pIndexBuilder == null) throw new NullPointerException();
    this.pIndexBuilder = pIndexBuilder;
  }

  String pIndexBuilder() {
    return this.pIndexBuilder;
  }

  private String rIndexBuilder() {
    return this.mStringBuilderBuild.pIndexBuilder();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("sb");
    sb.append(rIndexBuilder());
    sb.append(".toString()");
    return sb.toString();
  }

<<<<<<< HEAD
=======
=======
=======
import java.util.*;

public class MStringBuilderBuild extends Macro{
>>>>>>> object-macro2.1

    private String field_IndexBuilder;


    public MStringBuilderBuild(String pIndexBuilder){

        this.setPIndexBuilder(pIndexBuilder);


    }

    private void setPIndexBuilder( String pIndexBuilder ){
        if(pIndexBuilder == null){
            throw ObjectMacroException.parameterNull("IndexBuilder");
        }

        this.field_IndexBuilder = pIndexBuilder;
    }

<<<<<<< HEAD
>>>>>>> Correctifs objectmacro2-java(back)
=======
>>>>>>> object-macro2.1
    private String buildIndexBuilder(){

        return this.field_IndexBuilder;
    }

    private String getIndexBuilder(){

        return this.field_IndexBuilder;
    }


    @Override
    void apply(
            InternalsInitializer internalsInitializer){

        internalsInitializer.setStringBuilderBuild(this);
    }

   @Override
    public String build(){

        BuildState buildState = this.build_state;

        if(buildState == null){
            buildState = new BuildState();
        }
        else if(buildState.getExpansion() == null){
            throw ObjectMacroException.cyclicReference("StringBuilderBuild");
        }
        else{
            return buildState.getExpansion();
        }
        this.build_state = buildState;

        

        

        StringBuilder sb0 = new StringBuilder();

        sb0.append("sb");
        sb0.append(buildIndexBuilder());
        sb0.append(".toString()");

        buildState.setExpansion(sb0.toString());
        return sb0.toString();
    }

    @Override
    String build(Context context) {
        return build();
    }
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> Mise à jour Visiteur - Build OK
}
=======
}
>>>>>>> Correctifs objectmacro2-java(back)
=======
}
>>>>>>> object-macro2.1
