/* This file was generated by SableCC's ObjectMacro. */

#ifndef LINKEDLIST_H
#define LINKEDLIST_H

extern struct LinkedListVT VT_LinkedList;
extern void *HT_LinkedList[];

typedef struct LinkedList
{
    struct LinkedListVT (*vt)
    struct Node *nodes;
}

typedef struct LinkedListVT
{
    int hl;
    void* (*ht)[];
    void (*push)(struct LinkedList*, void *new_data, size_t data_size);
}

LinkedList* new_LinkedList();
void free_LinkedList(struct LinkedList*);

void LinkedList_push(struct LinkedList*, void *new_data, size_t data_size);

#endif //LINKEDLIST_H