/* This file was generated by SableCC's ObjectMacro. */

#ifndef LINKEDLISTNODE_H
#define LINKEDLISTNODE_H

deftype struct Node
{
    void *data;
    struct Node *next;
} Node;

#endif //LINKEDLISTNODE_H