before_script :
- apt-get update

test3.7:
  image : frekele/ant
  script:
  - cd ant-files
  - mv lib/sablecc.jar $ANT_HOME/lib/sablecc.jar
  - ant development
  - java -jar lib/sablecc.jar grammars/objectmacro.sablecc3 -d src
