language: java
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> Add travis support to run all tests
before_install:
    - wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.2-bin.tar.gz
    - tar -xzvf apache-ant-1.10.2-bin.tar.gz
    - mv apache-ant-1.10.2 apache-ant
    - export PATH=apache-ant/bin:$PATH
    - export ANT_HOME=apache-ant

install:
  - wget https://sourceforge.net/projects/sablecc/files/SableCC/3.7/sablecc-3.7.zip
  - unzip sablecc-3.7.zip
  - mv sablecc-3.7/lib/sablecc.jar $ANT_HOME/lib
<<<<<<< HEAD
=======
>>>>>>> Add travis to fork
=======
>>>>>>> Add travis support to run all tests
=======
>>>>>>> Changement Objectmacro-back

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
  - ./utils/run-all-tests
=======
  - ant -f ant-files/build.xml
>>>>>>> Add travis to fork
=======
  - ./utils/run-all-tests
>>>>>>> Add travis support to run all tests
=======
  - ant -f ant-files/build.xml
>>>>>>> Changement Objectmacro-back
