/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.c.macro;

import java.util.*;

public class MInclude extends Macro{
    
    private String field_IncludeName;
    
    
    
    
    public MInclude(String pIncludeName){
    
            this.setPIncludeName(pIncludeName);
    
    }
    
    
    private void setPIncludeName( String pIncludeName ){
        if(pIncludeName == null){
            throw ObjectMacroException.parameterNull("IncludeName");
        }
    
        this.field_IncludeName = pIncludeName;
    }
    
    
    private String buildIncludeName(){
    
        return this.field_IncludeName;
    }
    
    
    private String getIncludeName(){
    
        return this.field_IncludeName;
    }
    
    
    
    
    
    @Override
     void apply(
             InternalsInitializer internalsInitializer){
    
         internalsInitializer.setInclude(this);
     }
    
    
    @Override
    public String build(){
    
        BuildState buildState = this.build_state;
    
        if(buildState == null){
            buildState = new BuildState();
        }
        else if(buildState.getExpansion() == null){
            throw ObjectMacroException.cyclicReference("Include");
        }
        else{
            return buildState.getExpansion();
        }
        this.build_state = buildState;
        List<String> indentations = new LinkedList<>();
        StringBuilder sbIndentation = new StringBuilder();
    
        
        
    
        StringBuilder sb0 = new StringBuilder();
    
        sb0.append("#");
        sb0.append("include \"M");
        sb0.append(buildIncludeName());
        sb0.append(".h\"");
    
        buildState.setExpansion(sb0.toString());
        return sb0.toString();
    }
    
    
    @Override
    String build(Context context) {
     return build();
    }
    private String applyIndent(
                            String macro,
                            String indent){

            StringBuilder sb = new StringBuilder();
            String[] lines = macro.split( "\n");

            if(lines.length > 1){
                for(int i = 0; i < lines.length; i++){
                    String line = lines[i];
                    sb.append(indent).append(line);

                    if(i < lines.length - 1){
                        sb.append(LINE_SEPARATOR);
                    }
                }
            }
            else{
                sb.append(indent).append(macro);
            }

            return sb.toString();
    }
}