/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.c.macro;

import java.util.*;

public class MParamStringArg extends Macro{
    
    private final List<Macro> list_ParamType;
    
    private DSeparator ParamTypeSeparator;
    
    private DBeforeFirst ParamTypeBeforeFirst;
    
    private DAfterLast ParamTypeAfterLast;
    
    private DNone ParamTypeNone;
    
    private final InternalValue ParamTypeValue;
    
    private final List<Macro> list_ParamArg;
    
    private DSeparator ParamArgSeparator;
    
    private DBeforeFirst ParamArgBeforeFirst;
    
    private DAfterLast ParamArgAfterLast;
    
    private DNone ParamArgNone;
    
    private final InternalValue ParamArgValue;
    
    
    private final Context ParamTypeContext = new Context();
    
    private final Context ParamArgContext = new Context();
    
    
    public MParamStringArg(){
    
        this.list_ParamType = new ArrayList<>();
        this.list_ParamArg = new ArrayList<>();
    
        this.ParamTypeValue = new InternalValue(this.list_ParamType, this.ParamTypeContext);
        this.ParamArgValue = new InternalValue(this.list_ParamArg, this.ParamArgContext);
    }
    
    
    public void addParamType(MParamArgType macro){
        if(macro == null){
            throw ObjectMacroException.parameterNull("ParamType");
        }
                if(this.build_state != null){
                    throw ObjectMacroException.cannotModify("ParamArgType");
                }
    
        this.list_ParamType.add(macro);
        this.children.add(macro);
        Macro.cycleDetector.detectCycle(this, macro);
    }
    
    public void addParamArg(MParamArgName macro){
        if(macro == null){
            throw ObjectMacroException.parameterNull("ParamArg");
        }
                if(this.build_state != null){
                    throw ObjectMacroException.cannotModify("ParamArgName");
                }
    
        this.list_ParamArg.add(macro);
        this.children.add(macro);
        Macro.cycleDetector.detectCycle(this, macro);
    }
    
    
    private String buildParamType(){
        StringBuilder sb = new StringBuilder();
        Context local_context = ParamTypeContext;
        List<Macro> macros = this.list_ParamType;
    
        int i = 0;
        int nb_macros = macros.size();
        String expansion = null;
    
        if(this.ParamTypeNone != null){
            sb.append(this.ParamTypeNone.apply(i, "", nb_macros));
        }
    
        for(Macro macro : macros){
            expansion = macro.build(local_context);
    
            if(this.ParamTypeBeforeFirst != null){
                expansion = this.ParamTypeBeforeFirst.apply(i, expansion, nb_macros);
            }
    
            if(this.ParamTypeAfterLast != null){
                expansion = this.ParamTypeAfterLast.apply(i, expansion, nb_macros);
            }
    
            if(this.ParamTypeSeparator != null){
                expansion = this.ParamTypeSeparator.apply(i, expansion, nb_macros);
            }
    
            sb.append(expansion);
            i++;
        }
    
        return sb.toString();
    }
    
    private String buildParamArg(){
        StringBuilder sb = new StringBuilder();
        Context local_context = ParamArgContext;
        List<Macro> macros = this.list_ParamArg;
    
        int i = 0;
        int nb_macros = macros.size();
        String expansion = null;
    
        if(this.ParamArgNone != null){
            sb.append(this.ParamArgNone.apply(i, "", nb_macros));
        }
    
        for(Macro macro : macros){
            expansion = macro.build(local_context);
    
            if(this.ParamArgBeforeFirst != null){
                expansion = this.ParamArgBeforeFirst.apply(i, expansion, nb_macros);
            }
    
            if(this.ParamArgAfterLast != null){
                expansion = this.ParamArgAfterLast.apply(i, expansion, nb_macros);
            }
    
            if(this.ParamArgSeparator != null){
                expansion = this.ParamArgSeparator.apply(i, expansion, nb_macros);
            }
    
            sb.append(expansion);
            i++;
        }
    
        return sb.toString();
    }
    
    
    private InternalValue getParamType(){
        return this.ParamTypeValue;
    }
    
    private InternalValue getParamArg(){
        return this.ParamArgValue;
    }
    
    private void initParamTypeInternals(Context context){
        for(Macro macro : this.list_ParamType){
            macro.apply(new InternalsInitializer("ParamType"){
                @Override
                void setParamArgType(MParamArgType mParamArgType){
                
                    
                    
                }
            });
        }
    }
    
    private void initParamArgInternals(Context context){
        for(Macro macro : this.list_ParamArg){
            macro.apply(new InternalsInitializer("ParamArg"){
                @Override
                void setParamArgName(MParamArgName mParamArgName){
                
                    
                    
                }
            });
        }
    }
    
    
    private void initParamTypeDirectives(){
        
    }
    
    private void initParamArgDirectives(){
        
    }
    
    @Override
     void apply(
             InternalsInitializer internalsInitializer){
    
         internalsInitializer.setParamStringArg(this);
     }
    
    
    @Override
    public String build(){
    
        BuildState buildState = this.build_state;
    
        if(buildState == null){
            buildState = new BuildState();
        }
        else if(buildState.getExpansion() == null){
            throw ObjectMacroException.cyclicReference("ParamStringArg");
        }
        else{
            return buildState.getExpansion();
        }
        this.build_state = buildState;
        List<String> indentations = new LinkedList<>();
        StringBuilder sbIndentation = new StringBuilder();
    
        initParamTypeDirectives();
        initParamArgDirectives();
        
        initParamTypeInternals(null);
        initParamArgInternals(null);
    
        StringBuilder sb0 = new StringBuilder();
    
        sb0.append(buildParamType());
        sb0.append(" ");
        sb0.append(buildParamArg());
    
        buildState.setExpansion(sb0.toString());
        return sb0.toString();
    }
    
    
    @Override
    String build(Context context) {
     return build();
    }
    private String applyIndent(
                            String macro,
                            String indent){

            StringBuilder sb = new StringBuilder();
            String[] lines = macro.split( "\n");

            if(lines.length > 1){
                for(int i = 0; i < lines.length; i++){
                    String line = lines[i];
                    sb.append(indent).append(line);

                    if(i < lines.length - 1){
                        sb.append(LINE_SEPARATOR);
                    }
                }
            }
            else{
                sb.append(indent).append(macro);
            }

            return sb.toString();
    }
}