/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.c.macro;

import java.util.*;

public class MStringBuilderH extends Macro{
    
    
    
    
    
    public MStringBuilderH(){
    
    
    }
    
    
    
    
    
    
    
    
    
    
    
    @Override
     void apply(
             InternalsInitializer internalsInitializer){
    
         internalsInitializer.setStringBuilderH(this);
     }
    
    
    @Override
    public String build(){
    
        BuildState buildState = this.build_state;
    
        if(buildState == null){
            buildState = new BuildState();
        }
        else if(buildState.getExpansion() == null){
            throw ObjectMacroException.cyclicReference("StringBuilderH");
        }
        else{
            return buildState.getExpansion();
        }
        this.build_state = buildState;
        List<String> indentations = new LinkedList<>();
        StringBuilder sbIndentation = new StringBuilder();
    
        
        
    
        StringBuilder sb0 = new StringBuilder();
    
        MHeader minsert_5 = new MHeader();
        
        
        sb0.append(minsert_5.build(null));
        sb0.append(LINE_SEPARATOR);
        sb0.append(LINE_SEPARATOR);
        sb0.append("#");
        sb0.append("ifndef STRINGBUILDER_H");
        sb0.append(LINE_SEPARATOR);
        sb0.append("#");
        sb0.append("define STRINGBUILDER_H");
        sb0.append(LINE_SEPARATOR);
        sb0.append(LINE_SEPARATOR);
        sb0.append("#");
        sb0.append("include <stddef.h>");
        sb0.append(LINE_SEPARATOR);
        sb0.append("#");
        sb0.append("include <stdbool.h>");
        sb0.append(LINE_SEPARATOR);
        sb0.append(LINE_SEPARATOR);
        sb0.append("extern struct Stringbuilder_VT VT_Stringbuilder;");
        sb0.append(LINE_SEPARATOR);
        sb0.append("extern void *HT_Stringbuilder[];");
        sb0.append(LINE_SEPARATOR);
        sb0.append("static const char LINE_SEPARATOR[] = \"\\n\";");
        sb0.append(LINE_SEPARATOR);
        sb0.append(LINE_SEPARATOR);
        sb0.append("typedef struct Stringbuilder");
        sb0.append(LINE_SEPARATOR);
        sb0.append("{");
        sb0.append(LINE_SEPARATOR);
        sb0.append("    struct Stringbuilder_VT (*vt);");
        sb0.append(LINE_SEPARATOR);
        sb0.append("    char* mem;");
        sb0.append(LINE_SEPARATOR);
        sb0.append("    size_t count;");
        sb0.append(LINE_SEPARATOR);
        sb0.append("    size_t cap;");
        sb0.append(LINE_SEPARATOR);
        sb0.append("} Stringbuilder;");
        sb0.append(LINE_SEPARATOR);
        sb0.append(LINE_SEPARATOR);
        sb0.append("typedef struct Stringbuilder_VT");
        sb0.append(LINE_SEPARATOR);
        sb0.append("{");
        sb0.append(LINE_SEPARATOR);
        sb0.append("    int hl;");
        sb0.append(LINE_SEPARATOR);
        sb0.append("    void* (*ht)[];");
        sb0.append(LINE_SEPARATOR);
        sb0.append("    bool (*append)(struct Stringbuilder*, char*);");
        sb0.append(LINE_SEPARATOR);
        sb0.append("    char* (*toString)(struct Stringbuilder*);");
        sb0.append(LINE_SEPARATOR);
        sb0.append("} Stringbuilder_VT;");
        sb0.append(LINE_SEPARATOR);
        sb0.append(LINE_SEPARATOR);
        sb0.append("Stringbuilder* new_Stringbuilder(size_t init_cap);");
        sb0.append(LINE_SEPARATOR);
        sb0.append("void free_Stringbuilder(struct Stringbuilder*);");
        sb0.append(LINE_SEPARATOR);
        sb0.append(LINE_SEPARATOR);
        sb0.append("bool Stringbuilder_append(struct Stringbuilder*, char*);");
        sb0.append(LINE_SEPARATOR);
        sb0.append("bool Stringbuilder_appendChar(struct Stringbuilder*, char);");
        sb0.append(LINE_SEPARATOR);
        sb0.append("char* Stringbuilder_toString(struct Stringbuilder*);");
        sb0.append(LINE_SEPARATOR);
        sb0.append(LINE_SEPARATOR);
        sb0.append("#");
        sb0.append("endif //STRINGBUILDER_H");
    
        buildState.setExpansion(sb0.toString());
        return sb0.toString();
    }
    
    
    @Override
    String build(Context context) {
     return build();
    }
    private String applyIndent(
                            String macro,
                            String indent){

            StringBuilder sb = new StringBuilder();
            String[] lines = macro.split( "\n");

            if(lines.length > 1){
                for(int i = 0; i < lines.length; i++){
                    String line = lines[i];
                    sb.append(indent).append(line);

                    if(i < lines.length - 1){
                        sb.append(LINE_SEPARATOR);
                    }
                }
            }
            else{
                sb.append(indent).append(macro);
            }

            return sb.toString();
    }
}